sudo: false
os: osx
language: node_js
node_js: "4.2"
osx_image: xcode 7.3

env: 
  # iOS 9.3
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-battery-status
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-camera
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-console
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-contacts
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-device
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-device-motion
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-device-orientation
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-dialogs
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-file
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-file-transfer
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-geolocation
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-globalization
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-inappbrowser
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-media
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-media-capture
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-network-information
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-screen-orientation
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-splashscreen
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-statusbar
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-vibration
  - PLATFORM=ios-9.3 PLUGIN=cordova-plugin-wkwebview-engine
  # iOS 10.0
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-battery-status
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-camera
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-console
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-contacts
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-device
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-device-motion
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-device-orientation
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-dialogs
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-file
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-file-transfer
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-geolocation
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-globalization
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-inappbrowser
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-media
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-media-capture
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-network-information
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-screen-orientation
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-splashscreen
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-statusbar
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-vibration
  - PLATFORM=ios-10.0 PLUGIN=cordova-plugin-wkwebview-engine

before_install:
  - npm cache clean -f
  - node --version
  - npm install -g ios-deploy

install:
  - git clone --depth=1 --branch=master https://github.com/apache/cordova-paramedic /tmp/paramedic && pushd /tmp/paramedic && npm install && popd
  - git clone --depth=1 --branch=master https://github.com/apache/cordova-coho /tmp/coho && pushd /tmp/coho && npm install && popd
  - git clone --depth=1 --branch=master https://github.com/apache/$PLUGIN /tmp/$PLUGIN
  # installing dev cordova
  - pushd /tmp && coho/coho repo-clone -r tools && popd
  - pushd /tmp && coho/coho npm-link && popd
  - pushd /tmp/cordova-cli && npm install && popd
  - /tmp/cordova-cli/bin/cordova -v

script:
  - PLUGINS_ARG="--plugin /tmp/$PLUGIN"
  - FTS_ARG="--fileTransferServer http://sheltered-retreat-43956.herokuapp.com"
  - CLI_ARG="--cli /tmp/cordova-cli/bin/cordova"
  - node /tmp/paramedic/main.js --config pr/$PLATFORM $PLUGINS_ARG $FTS_ARG $CLI_ARG --shouldUseSauce --buildName travis-periodic-$TRAVIS_JOB_NUMBER
